# Generated by Django 5.1.4 on 2025-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandanalysis',
            name='excel_link',
        ),
        migrations.AddField(
            model_name='search',
            name='excel_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
