# Generated by Django 5.1.4 on 2025-03-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0004_category_brand_categories_brandcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandfeature',
            name='description',
        ),
        migrations.CreateModel(
            name='BrandFeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='analiz.brandfeature')),
            ],
            options={
                'unique_together': {('feature', 'value')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='brandfeaturevalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='brandfeaturevalue',
            name='feature_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_values', to='analiz.brandfeatureoption'),
        ),
        migrations.AlterUniqueTogether(
            name='brandfeaturevalue',
            unique_together={('brand', 'feature_option')},
        ),
        migrations.RemoveField(
            model_name='brandfeaturevalue',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='brandfeaturevalue',
            name='value',
        ),
    ]
