# Generated by Django 5.1.4 on 2025-03-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0005_remove_brandfeature_description_brandfeatureoption_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandCategory',
        ),
    ]
