# Generated by Django 5.1.4 on 2025-03-03 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0007_subscriptionplan_usersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='expires_at',
            field=models.DateTimeField(default='2025-12-31 23:59:59'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='analiz.subscriptionplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='remaining_brand_credits',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
