# Generated by Django 5.1.4 on 2025-03-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0008_alter_usersubscription_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='brand_access_limit',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='remaining_brand_credits',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='basic_brand_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='filtered_brand_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='remaining_basic_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='remaining_filtered_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
