# Generated by Django 5.1.4 on 2025-04-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0009_remove_subscriptionplan_brand_access_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='payment_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
